Documentation fixes
circe/circe pull request #1834
Opened 2021-10-01 11:23 UTC by mattkohl

The main change here is to standardize how module names are styled in the documentation. Instead of being sometimes marked out & others not, now every time a module is referred to, it's enclosed in back-ticks, as in `generic-extras`.

The PR includes a couple of grammatical & case adjustments as well.

Thanks for all the work you 🙏

2021-11-19 20:07 UTC, zmccoy approved these changes

2021-11-19 20:11 UTC, zarthross commented on docs/src/main/tut/codecs/custom-codecs.md
> +`generic-extras` module does provide two ways to transform your case class member
We need to keep the 'experimental' verbiage here for now.  The future of `generic-extras` is still unknown and that repo is labeled as 'experimental'.

2021-11-19 20:14 UTC, zarthross requested changes

2021-11-19 20:14 UTC, zarthross commented on docs/src/main/tut/codecs/custom-codecs.md
> +It's worth noting that if you don't want to use the `generic-extras` module, the
Same as the other note.  Want people to consider it experimental, know that it may not be supported in exactly the same way in the future.

2021-11-20 19:03 UTC, zmccoy approved these changes
Thanks for fixing those up!

2021-11-21 13:16 UTC, zarthross approved these changes

2021-11-21 14:01 UTC, merged